name: pytest

on:
  - push


jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up for Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          pipenv install
      - name: Run pytest
        run: pipenv run pytest
  